excluded:
  - Pods/
  - R.generated.swift
disabled_rules:
  - line_length
  - variable_name
  - force_cast
  - force_try
  - large_tuple
  - no_space_in_method_call
file_length: 600
line_length: 400
type_body_length: 600
type_name:
  min_length: 3
  max_length: 50
identifier_name:
  min_length:
    warning: 1
function_body_length: 200
cyclomatic_complexity:
  - 70
  - 90
function_parameter_count:
  - 15
  - 20
